name: capstonesproject2024
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.14.0
  cloud_firestore: ^4.9.0
  excel: ^2.0.5
  path_provider: ^2.0.14
  permission_handler: ^11.2.0
  csv: ^5.0.0
  file_picker: ^5.3.0
  path: ^1.8.0
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/ccs.png
    - assets/warriors.png
    - assets/ccswarriors.png
